web/router.ex
defmodule Librarian.Router do
  use Phoenix.Router

  import Passport.AuthenticationPlug
  pipeline :authentication do
    plug :require_login, [
      flash_key: :info,
      flash_msg: "You must be logged in.",
      redirect_to: "/login"
    ]
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :assign_current_user
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Librarian do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    # Login & Registration
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/signup", RegistrationController, :new
    post "/signup", RegistrationController, :create
  end

  scope "/api", Librarian do
    pipe_through :api
    get "/search", SearchController, :index
  end

  scope "/profile", Librarian do
    pipe_through [:browser, :authentication]

    get "/", ProfileController, :show
    get "/edit", ProfileController, :edit
    # resources "/users", UserController
  end

  scope "/authentication", Librarian do
    pipe_through [:browser, :authentication]

    scope "/github", Authentication do
      get "/", GithubController, :index
      get "/callback", GithubController, :callback
    end

    scope "/google", Authentication do
      get "/", GoogleController, :index
      get "/callback", GoogleController, :callback
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Librarian do
  #   pipe_through :api
  # end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end
end

web/views/layout_view.ex
defmodule Librarian.LayoutView do
  use Librarian.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Librarian</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Librarian</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= if logged_in?(@conn) do %>
            <li>
              <a href="<%= profile_path @conn, :show %>">Profile</a>
            </li>
            <li>
              <a href="<%= session_path @conn, :delete %>">Logout</a>
            </li>
          <% else %>
            <li>
              <a href="<%= registration_path @conn, :new %>">Signup</a>
            </li>
            <li>
              <a href="<%= session_path @conn, :new %>">Login</a>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <% flash_info = get_flash @conn, :info %>
      <%= if flash_info do %>
        <div class="alert alert-warning" role="alert"><%= flash_info %></div>
      <% end %>
      <% flash_error = get_flash @conn, :error %>
      <%= if flash_error do %>
        <div class="alert alert-success" role="alert"><%= flash_error %></div>
      <% end %>
      <%= @inner %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"</script>
    <script>require("/web/static/app")</script>
  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Librarian</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Librarian</a>
        </div>
        <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <%= if logged_in?(@conn) do %>
            <li>
              <a href="<%= session_path @conn, :delete %>">Logout</a>
            </li>
          <% else %>
            <li>
              <a href="<%= registration_path @conn, :new %>">Signup</a>
            </li>
            <li>
              <a href="<%= session_path @conn, :new %>">Login</a>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <% flash_info = get_flash @conn, :info %>
      <%= if flash_info do %>
        <div class="alert alert-warning" role="alert"><%= flash_info %></div>
      <% end %>
      <% flash_error = get_flash @conn, :error %>
      <%= if flash_error do %>
        <div class="alert alert-success" role="alert"><%= flash_error %></div>
      <% end %>
      <%= @inner %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"</script>
    <script>require("/web/static/app")</script>
  </body>
</html>